# Generated by Django 3.0.3 on 2020-04-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunote', '0004_auto_20200328_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
